FROM node:20-alpine as build
WORKDIR /app

COPY frontend/package*.json ./
RUN npm install
COPY frontend/ .

RUN npm run build

FROM python:3.10-slim
WORKDIR /app

COPY backend/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY backend/ .

COPY --from=build /app/dist ./static_dist

CMD ["python", "app.py"]